import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import FormCard from "../components/FormCard";
import Button from "../components/Button";
import OTPInput from "../components/OTPInput";
import { ShieldCheck, Clock } from "lucide-react";

const MFAVerification = () => {
  const navigate = useNavigate();
  const [otp, setOtp] = useState(["", "", "", "", "", ""]);
  const [isLoading, setIsLoading] = useState(false);
  const [timeLeft, setTimeLeft] = useState(30);

  useEffect(() => {
    if (timeLeft <= 0) return;

    const timerId = setInterval(() => {
      setTimeLeft((prev) => prev - 1);
    }, 1000);

    return () => clearInterval(timerId);
  }, [timeLeft]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    const otpValue = otp.join("");

    if (otpValue.length !== 6) return;

    setIsLoading(true);

    // Simulate API call
    setTimeout(() => {
      // TODO: Call backend API to verify MFA
      // 1. Make a POST request to '/api/verify-mfa' with { otp: otpValue }
      // 2. If successful (200 OK): Save the final Auth Token (JWT) in localStorage/cookies to establish an authenticated session.
      // 3. Navigate to the main dashboard.
      // 4. If error (400 Invalid OTP): Show an error message to the user, clear the OTP input, and let them try again.

      setIsLoading(false);
      // Navigate to dashboard on success
      alert("Verification successful! Redirecting to Dashboard...");
      navigate('/');
    }, 1000);
  };

  const isOtpComplete = otp.every((val) => val !== "");

  const handleResend = () => {
    // Reset timer and clear OTP
    setTimeLeft(30);
    setOtp(["", "", "", "", "", ""]);
  };

  return (
    <FormCard
      title="Two-Step Verification"
      subtitle="Enter the verification code generated by your authenticator app."
    >
      <form onSubmit={handleSubmit} className="flex flex-col items-center">
        <div className="bg-indigo-50 p-4 rounded-full mb-6">
          <ShieldCheck className="w-12 h-12 text-indigo-600" />
        </div>

        <OTPInput value={otp} onChange={setOtp} />

        <div className="flex items-center gap-2 text-sm text-slate-500 mb-6 font-medium">
          <Clock className="w-4 h-4" />
          <span className={timeLeft < 10 ? "text-red-500" : ""}>
            Code expires in 00:{timeLeft.toString().padStart(2, "0")}
          </span>
        </div>

        <div className="w-full">
          <Button
            type="submit"
            isLoading={isLoading}
            disabled={!isOtpComplete || timeLeft === 0}
          >
            Verify
          </Button>
        </div>

        {timeLeft === 0 && (
          <button
            type="button"
            onClick={handleResend}
            className="mt-6 text-sm text-indigo-600 font-medium hover:underline"
          >
            I didn't get a code
          </button>
        )}
      </form>
    </FormCard>
  );
};

export default MFAVerification;
