import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import FormCard from '../components/FormCard';
import Button from '../components/Button';
import OTPInput from '../components/OTPInput';
import { QrCode } from 'lucide-react';

const QRSetup = () => {
  const navigate = useNavigate();
  const [otp, setOtp] = useState(['', '', '', '', '', '']);
  const [isLoading, setIsLoading] = useState(false);
  const [qrCodeUrl] = useState('placeholder'); // TODO: Add setQrCodeUrl when fetching from backend

  useEffect(() => {
    // Simulate fetching QR code on mount
    // TODO: Fetch QR code from backend
    // 1. Make a GET request to '/api/mfa/setup' using the temporary session token acquired during login.
    // 2. The backend should return a QR code image URL or base64 data, and a secret key text fallback.
    // 3. Update the `qrCodeUrl` state with the received image data.
    // 4. Handle errors if the user is unauthorized or already has MFA set up.
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    const otpValue = otp.join('');
    
    if (otpValue.length !== 6) return;
    
    setIsLoading(true);

    // Simulate API call
    setTimeout(() => {
      // TODO: Send OTP to backend for verification
      // 1. Make a POST request to '/api/mfa/setup/verify' with { otp: otpValue }
      // 2. If successful (200 OK): MFA is now active. Save the final Auth Token (JWT) in localStorage/cookies.
      // 3. Navigate to the main dashboard.
      // 4. If error (400 Invalid OTP): Show an error message "Invalid OTP, please try again".
      
      setIsLoading(false);
      navigate('/verify-mfa');
    }, 1000);
  };

  const isOtpComplete = otp.every(val => val !== '');

  return (
    <FormCard 
      title="Secure Your Account" 
      subtitle="Set up Multi-Factor Authentication using an authenticator app like Proton Authenticator."
    >
      <form onSubmit={handleSubmit} className="flex flex-col items-center">
        <div className="bg-slate-100 p-4 rounded-xl border border-slate-200 mb-6 flex flex-col items-center justify-center w-48 h-48">
          {qrCodeUrl === 'placeholder' ? (
            <QrCode className="w-32 h-32 text-slate-400" strokeWidth={1} />
          ) : (
            <img src={qrCodeUrl} alt="MFA QR Code" className="w-full h-full object-contain" />
          )}
        </div>
        
        <p className="text-sm text-slate-600 text-center mb-2">
          Scan the QR code above and enter the 6-digit code generated by your app.
        </p>

        <OTPInput value={otp} onChange={setOtp} />
        
        <div className="w-full mt-4">
          <Button type="submit" isLoading={isLoading} disabled={!isOtpComplete}>
            Verify and Enable
          </Button>
        </div>
      </form>
    </FormCard>
  );
};

export default QRSetup;
